(define (square x) (* x x))
(square (square (square 2)))
(define (average x y) (/ (+ x y) 2))
(average 2 8)
(define (mean-square-average x y) (average (square x) (square y)))
(mean-square-average 10 12)
(mean-square-average (square 4) (square 5))
(define (abs x) (cond ((< x 0) (- x)) ((= x 0) 0) ((> x 0) x)))
(abs 0)
(abs 111)
(abs -1107)
(+ 2 (abs -44))
(define (sqrt x)
  (define (improve guess)
    (average guess (/ x guess)))
  (define (good-enough? guess)
    (< (abs (- guess (/ x guess))) 0.001))
  ( define (try guess)
    (if (good-enough? guess)
        guess
        (try (improve guess))))
  (try 1))
(sqrt 4)
(sqrt 123454321)
(sqrt 0.04)
(sqrt 2)

